### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by krambriw** [kazuhitoyokoi/node-red-contrib-tensorflow#8]
Hi, when using your node (cocossd) it is detecting fine and I just have a question related to performance. Running NR flow on a raspberry pi and comparing the detection time with _node-red-contrib-tfjs-coco-ssd_ that is much faster, basically detecting the same objects

Do you happen to know what differs? Does your node use the same library? Do you use hw acceleration (using GPU) when it is supported like in the raspberry pi?

Best regards & thank you!
Walter

**Comment by kazuhitoyokoi** [comment]
@krambriw Thank you for your question. As you said, performance is totally different from `node-red-contrib-tfjs-coco-ssd` because `node-red-contrib-tfjs-coco-ssd` uses binary code for specific CPUs. `node-red-contrib-tfjs-coco-ssd` is natural implantation but I implemented my node as pure JavaScript for all of CPUs (For example, Apple M1, AIX, Raspberry Pi Zero).

**Comment by krambriw** [comment]
Thank you for your explanation, fine, understood!
Best regards, Walter
